/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tracks/paris-bis-transformed.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    N_Audience_NoMove_01_M_Cmn_AudienceModel_0: THREE.Mesh
    F_Building_M_Cmn_MainColor_Detail_0: THREE.Mesh
    F_Building_M_Mobp1_Textures01_0: THREE.Mesh
    N_MansionObj_01_M_Mobp1_kanban_0: THREE.Mesh
    Rainbow_model_M_Mobp1_Rainbow_0: THREE.Mesh
    F_Ground_01_M_Mobp1_Water_0: THREE.Mesh
    Gmob_Paris_VR_M_Mobp1_VR_0: THREE.Mesh
    N_Building_002_M_Mobp1_gaisenmon_tex_0: THREE.Mesh
    N_Road_Ground_M_Mobp1_Road_A_0: THREE.Mesh
    N_Road_Ground_M_Mobp1_Road_B_0: THREE.Mesh
    ShadowCollision_M_Cmn_ShadowCollision_0: THREE.Mesh
  }
  materials: {
    M_Cmn_AudienceModel: THREE.MeshStandardMaterial
    M_Cmn_MainColor_Detail: THREE.MeshStandardMaterial
    M_Mobp1_Textures01: THREE.MeshStandardMaterial
    M_Mobp1_kanban: THREE.MeshStandardMaterial
    M_Mobp1_Rainbow: THREE.MeshStandardMaterial
    M_Mobp1_Water: THREE.MeshStandardMaterial
    M_Mobp1_VR: THREE.MeshStandardMaterial
    M_Mobp1_gaisenmon_tex: THREE.MeshStandardMaterial
    M_Mobp1_Road_A: THREE.MeshStandardMaterial
    M_Mobp1_Road_B: THREE.MeshStandardMaterial
    M_Cmn_ShadowCollision: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/paris-bis-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.N_Audience_NoMove_01_M_Cmn_AudienceModel_0.geometry} material={materials.M_Cmn_AudienceModel} scale={0.01} />
      <mesh geometry={nodes.F_Building_M_Cmn_MainColor_Detail_0.geometry} material={materials.M_Cmn_MainColor_Detail} scale={0.01} />
      <mesh geometry={nodes.F_Building_M_Mobp1_Textures01_0.geometry} material={materials.M_Mobp1_Textures01} scale={0.01} />
      <mesh geometry={nodes.N_MansionObj_01_M_Mobp1_kanban_0.geometry} material={materials.M_Mobp1_kanban} scale={0.01} />
      <mesh geometry={nodes.Rainbow_model_M_Mobp1_Rainbow_0.geometry} material={materials.M_Mobp1_Rainbow} position={[-0.16, 0.001, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.F_Ground_01_M_Mobp1_Water_0.geometry} material={materials.M_Mobp1_Water} scale={0.01} />
      <mesh geometry={nodes.Gmob_Paris_VR_M_Mobp1_VR_0.geometry} material={materials.M_Mobp1_VR} position={[0, -4.511, 0]} scale={0.01} />
      <mesh geometry={nodes.N_Building_002_M_Mobp1_gaisenmon_tex_0.geometry} material={materials.M_Mobp1_gaisenmon_tex} scale={0.01} />
      <mesh geometry={nodes.N_Road_Ground_M_Mobp1_Road_A_0.geometry} material={materials.M_Mobp1_Road_A} scale={0.01} />
      <mesh geometry={nodes.N_Road_Ground_M_Mobp1_Road_B_0.geometry} material={materials.M_Mobp1_Road_B} scale={0.01} />
      <mesh geometry={nodes.ShadowCollision_M_Cmn_ShadowCollision_0.geometry} material={materials.M_Cmn_ShadowCollision} position={[0, 0.002, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/paris-bis-transformed.glb')
